spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/languages?useSSL=false
    password: root
  cloud:
    config:
      import-check:
        enabled: 'true'
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
server:
  error:
    include-binding-errors: always
    include-message: always